// ============================================
// JANISHAMMER INJECTOR CORE v1.0
// 100% STABLE - Navbar, Footer, GA, Fonts, FA, Mobile Logic
// DO NOT EDIT THIS FILE
// ============================================

(function() {
    // ===== LOAD EXTERNAL ASSETS =====
    function loadAssets() {
        // Google Fonts
        const fonts = document.createElement('link');
        fonts.rel = 'stylesheet';
        fonts.href = 'https://fonts.googleapis.com/css2?family=Inter:wght@300..700&family=Sora:wght@300..700&family=Outfit:wght@300..700&family=Quicksand:wght@400;500;600&family=Montserrat:wght@300..700&display=swap';
        document.head.appendChild(fonts);
        
        // Font Awesome
        const fa = document.createElement('link');
        fa.rel = 'stylesheet';
        fa.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css';
        document.head.appendChild(fa);
    }

    // ===== GOOGLE ANALYTICS =====
    function initGoogleAnalytics() {
        const GA_ID = 'G-XXXXXXXXXX';
        const script = document.createElement('script');
        script.async = true;
        script.src = `https://www.googletagmanager.com/gtag/js?id=${GA_ID}`;
        document.head.appendChild(script);
        
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', GA_ID);
    }

    // ===== BUILD NAVBAR (uses window.BRANDS from config) =====
    function buildNavbar() {
    const brand = window.CURRENT_BRAND || 'janishammer';
    const config = window.BRANDS ? window.BRANDS[brand] : null;
    
    if (!config) return '';
    
    return `
        <nav class="navbar">
            <div class="nav-container">
                <div class="nav-left">
                    <img src="${config.logoLight}" alt="${config.name}">
                </div>
                
                <div class="nav-center">
                    <ul class="nav-menu">
                        <li class="nav-item">
                            <a href="#" class="nav-link">Lifestyle <i class="fas fa-chevron-down"></i></a>
                            <div class="dropdown">
                                <a href="https://flow.janishammer.com" class="dropdown-item ${brand === 'flow' ? 'current' : ''}">Flow</a>
                                <a href="https://daje.janishammer.com" class="dropdown-item ${brand === 'daje' ? 'current' : ''}">Daje</a>
                                <a href="https://i-flexthailand.com" class="dropdown-item ${brand === 'iflex' ? 'current' : ''}">I-Flex</a>
                                <a href="https://jade.janishammer.com" class="dropdown-item ${brand === 'jade' ? 'current' : ''}">Jade</a>
                            </div>
                        </li>
                        <li><a href="#" class="nav-link">Blog</a></li>
                        <li><a href="#" class="nav-link">Contact Us</a></li>
                    </ul>
                </div>
                
                <div class="nav-right">
                    <div class="language-selector">
                        <span class="active">EN</span> | <span>TH</span>
                    </div>
                    <div class="hamburger" id="janishammerHamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </div>
            </div>
        </nav>

        <div class="mobile-menu" id="janishammerMobileMenu">
            <ul class="mobile-menu-list">
                <li><a href="#" class="mobile-menu-link">Lifestyle</a>
                    <div class="mobile-dropdown">
                        <a href="https://flow.janishammer.com" class="mobile-dropdown-link ${brand === 'flow' ? 'current' : ''}">Flow</a>
                        <a href="https://daje.janishammer.com" class="mobile-dropdown-link ${brand === 'daje' ? 'current' : ''}">Daje</a>
                        <a href="https://i-flexthailand.com" class="mobile-dropdown-link ${brand === 'iflex' ? 'current' : ''}">I-Flex</a>
                        <a href="https://jade.janishammer.com" class="mobile-dropdown-link ${brand === 'jade' ? 'current' : ''}">Jade</a>
                    </div>
                </li>
                <li><a href="#" class="mobile-menu-link">Blog</a></li>
                <li><a href="#" class="mobile-menu-link">Contact Us</a></li>
            </ul>
        </div>
    `;
}

    // ===== BUILD FOOTER =====
    function buildFooter() {
        const brand = window.CURRENT_BRAND || 'janishammer';
        const config = window.BRANDS ? window.BRANDS[brand] : null;
        const year = new Date().getFullYear();
        
        if (!config) return '';
        
        return `
            <footer class="footer">
                <div class="footer-container">
                    <div class="footer-content">
                        <div class="footer-brand">
                            <h3>${config.name}</h3>
                            <p>${config.tagline}</p>
                            <div class="social-links">
                                <a href="${config.social.facebook}"><i class="fab fa-facebook-f"></i></a>
                                <a href="${config.social.instagram}"><i class="fab fa-instagram"></i></a>
                                <a href="${config.social.youtube}"><i class="fab fa-youtube"></i></a>
                                <a href="${config.social.tiktok}"><i class="fab fa-tiktok"></i></a>
                            </div>
                        </div>
                        <div class="footer-links">
                            <h4>Quick Links</h4>
                            <ul>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Products</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                        <div class="footer-contact">
                            <h4>Contact</h4>
                            <p><i class="fas fa-envelope"></i> ${config.contactEmail}</p>
                            <p><i class="fas fa-globe"></i> ${config.domain}</p>
                        </div>
                    </div>
                    <div class="footer-bottom">
                        <p>© ${year} ${config.name} · A Janishammer Brand</p>
                    </div>
                </div>
            </footer>
        `;
    }

    // ===== MOBILE MENU =====
    function initMobileMenu() {
        setTimeout(() => {
            const hamburger = document.getElementById('janishammerHamburger');
            const mobileMenu = document.getElementById('janishammerMobileMenu');
            
            if (hamburger && mobileMenu) {
                hamburger.addEventListener('click', () => {
                    hamburger.classList.toggle('active');
                    mobileMenu.classList.toggle('active');
                });
            }
        }, 100);
    }

    // ===== FAVICON =====
    function setFavicon() {
        const brand = window.CURRENT_BRAND || 'janishammer';
        const config = window.BRANDS ? window.BRANDS[brand] : null;
        
        if (!config || !config.favicon) return;
        
        document.querySelectorAll('link[rel*="icon"]').forEach(el => el.remove());
        
        const favicon = document.createElement('link');
        favicon.rel = 'icon';
        favicon.type = 'image/png';
        favicon.href = config.favicon;
        document.head.appendChild(favicon);
        
        const appleIcon = document.createElement('link');
        appleIcon.rel = 'apple-touch-icon';
        appleIcon.href = config.favicon;
        document.head.appendChild(appleIcon);
    }

    // ===== INIT =====
    function init() {
        // Wait for config to load first
        if (!window.BRANDS) {
            console.error('Janishammer: BRANDS config not loaded. Make sure injector-config.js loads first.');
            return;
        }
        
        loadAssets();
        setFavicon();
        document.body.insertAdjacentHTML('afterbegin', buildNavbar());
        document.body.insertAdjacentHTML('beforeend', buildFooter());
        initGoogleAnalytics();
        initMobileMenu();
        
        const brand = window.CURRENT_BRAND || 'janishammer';
        console.log(`✅ Janishammer Core loaded for ${window.BRANDS[brand].name}`);
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
